### ISSUE TITLE
/Menu Resets everytime you fly in or out

### ISSUE THREAD

**Issue by SeeTheGoombas** [RecklessRP2/rlrp-issue-tracker#11]
### Reporter

SeeTheGoombas

### Summary

Every time i fly in the changes i have made to my hide/ mini map such as disabling top-down view resets

### Steps to Reproduce

Fly in to the city make changes through /menu and then fly out and then fly back in

### Expected Behavior

Every change you made through /menu will stick with you

### Actual Results

Every change you made will reset

### Screenshots/Videos

I have none

**Comment by JSterlacci21** [comment]
Have you hit the save icon in the bottom left? Its dark so its hard to see but should be there. 
![image](https://github.com/user-attachments/assets/5e34286f-1739-4dc6-a15a-417188045da4)

**Comment by iMStokes** [comment]
Use the save icon to save your settings. :')
