### ISSUE TITLE
Trucking Payouts

### ISSUE THREAD

**Issue by TK-Phoenix** [RecklessRP2/rlrp-issue-tracker#12]
### Reporter

320367554478735381

### Summary

So doing the trucking jobs, the % multipliers aren't being added properly, if at all unfortunately.

### Steps to Reproduce

Do trucking and get skill points, use the skill points into any of the enhancements, and then do a trucking job, with the enhancement, to completion, and get paid (only the base amount)

### Expected Behavior

The expected behavior/result is to get paid at the end, with any enhancement bonus' added to the pay.

### Actual Results

The actual result is to only get paid the base amount ($125/$175)

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/imOf1lLY8zwG0CLWM/d1337iDLEYeS?invite=cr-MSxGYjQsMjAwMDg5MjAyLA

**Comment by Djmeowzle** [comment]
I was going to make the same post, the only bonus is for a convoy, and it's $1 more per person, which isn't anything. Also noticed today that the bonuses for long distance + fragile + etc are not adding on.
