### ISSUE TITLE
Drivers License/ID Cant be shown

### ISSUE THREAD

**Issue by SeeTheGoombas** [RecklessRP2/rlrp-issue-tracker#14]
### Reporter

SeeTheGoombas

### Summary

When you try and use your license or ID nothing gets shown information wise or pops up in your eyes at all

### Steps to Reproduce

Get a ID or Drivers license and use it 

### Expected Behavior

To show the license to you and the surrounding people or officer at traffic stop

### Actual Results

Nothing happens

**Comment by iMStokes** [comment]
This has been resolved with the latest update - which will go live on 8/9.
