### ISSUE TITLE
Bug Report - TITLE HERE

### ISSUE THREAD

**Issue by njost25** [RecklessRP2/rlrp-issue-tracker#18]
### Reporter

Nickj

### Summary

When going to talk to the PED underneath Olympic Freeway, he takes $100 to start the job but will then tell you there are not enough officers on duty

### Steps to Reproduce

Have $100 and talk to the PED to start the job

### Expected Behavior

Having the job be started

### Actual Results

He tells you the job is started and to wait for more information, then another message pops up saying not enough officers

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/inkKoH0eLKRN2wVQ1/d1337xCLnEHU?invite=cr-MSxRc20sMjAwMjQ1NjI1LA

**Comment by TK-Phoenix** [comment]
Also, just wont give you the job either. just ate the 100$
