### ISSUE TITLE
Bug Report - Missing Images

### ISSUE THREAD

**Issue by iGreatWhite** [RecklessRP2/rlrp-issue-tracker#21]
### Reporter

iGreatWhite

### Summary

Coke Bag does not have a picture, the same is also true with crack and meth.

### Steps to Reproduce

Put bag in inventory

### Expected Behavior

Pictures to represent the drugs

### Actual Results

No picture

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/18aaabb7-4a58-446f-a00c-8f48ca9fb1d3)

**Comment by iMStokes** [comment]
This has been resolved with the most recent patch. Thank you.
