### ISSUE TITLE
Bug Report - Electronic Kits

### ISSUE THREAD

**Issue by iGreatWhite** [RecklessRP2/rlrp-issue-tracker#23]
### Reporter

iGreatWhite

### Summary

The guy who you swap parts to does not give you an electronic kit when you try to purchase one from him.

### Steps to Reproduce

Buy an Electronic Kit

### Expected Behavior

To be given an electronic kit

### Actual Results

No electronic kit given

**Comment by DiazSasi** [comment]
i got same issue , i swap 30 parts and got 0 electric kit

**Comment by iMStokes** [comment]
This has been resolved with the most recent update.
