### ISSUE TITLE
Bug Report - TITLE HERE

### ISSUE THREAD

**Issue by MrPantz0** [RecklessRP2/rlrp-issue-tracker#25]
### Reporter

MrPantz

### Summary

No paint next fire hydrant.

### Steps to Reproduce

Drive to fire hydrant 

### Expected Behavior

Red Paint

### Actual Results

None

### Screenshots/Videos

![No Paint](https://github.com/user-attachments/assets/06c4b195-63e9-44f5-85a0-952d412862b8)

**Comment by Djmeowzle** [comment]
This is serious, i hope this get's address ASAP, otherwise, i don't think the server can function properly.
