### ISSUE TITLE
Suggestion - Vehicle Return Price

### ISSUE THREAD

**Issue by iGreatWhite** [RecklessRP2/rlrp-issue-tracker#26]
### Reporter

iGreatWhite

### Summary

Right now it costs $2,500 to return and drive your vehicle if it disappears. This is a bit highi in my opinion with how the economy is. I feel like the price should be more like $100-$250

### Reason

This would be a good change becasue some people took their cars out on finance and if we have to spend all our money on retrieving it every couple hours because it poofed this could get ridiculous.

**Comment by TK-Phoenix** [comment]
Honestly this, even 500$ wouldn't hurt so bad compared to the 2500$. Especially with how hard it is getting into a garage after I working on cars.
