### ISSUE TITLE
Opening Dumpsters

### ISSUE THREAD

**Issue by njost25** [RecklessRP2/rlrp-issue-tracker#3]
### Reporter

Nickj

### Summary

When attempting to 'Open Dumpster' it won't open. It says 'You can't open your inventory right now' while the loading bar is progressing.

### Steps to Reproduce

Go up to any dumpster and attempt to open it

### Expected Behavior

Should be able to open it as if it's a stash I assume

### Actual Results

Actual results does not allow you to open it

### Screenshots/Videos

F8 after attempting https://i.vgy.me/tXThac.png

**Comment by iMStokes** [comment]
This has been resolved with the most recent update.
