### ISSUE TITLE
Dumpster Diving

### ISSUE THREAD

**Issue by AnfewMac** [RecklessRP2/rlrp-issue-tracker#33]
### Reporter

antfew_mac

### Summary

Can we lower the chance of getting bit by a rat or stung by needles while digging through trash? You cant dig through 10 garbage cans without having to go to the hospital. Digging through trash gets you items for making money, however I end up using more than half the money going to the hospital. If we could buy gloves or something I would do that as well. Either would be great

### Reason

This would help with productivity for activities within the city.

**Comment by iMStokes** [comment]
This has been updated and reflected in the update that will be live on 8/9.


Thank you for your feedback.
