### ISSUE TITLE
Bug Report - TITLE HERE

### ISSUE THREAD

**Issue by itsohaa** [RecklessRP2/rlrp-issue-tracker#38]
### Reporter

itsohaa

### Summary

no photo for bags of coke 

### Steps to Reproduce

have coke 

### Expected Behavior

no photo need photo

### Actual Results

nothin dawg

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1269686679413723146/1270227732185354364/image.png?ex=66b2ef43&is=66b19dc3&hm=f9370418ae4f3c424e8557b5daf04d9b921599eccad7c27ead524dfac0e45221&

**Comment by iMStokes** [comment]
This has been resolved and will be live on 8/9.
