### ISSUE TITLE
Suggestion - Change Financing of Cars

### ISSUE THREAD

**Issue by Djmeowzle** [RecklessRP2/rlrp-issue-tracker#5]
### Reporter

Djmeowzle

### Summary

Currently Financing is done in 12 payments every 12 hours, 2 payments a day for 6 days. For some cars it is insanely expensive, costing 10 grand a payment, twice a day, meaning $20,000 a day for 6 days. The time crunch and payment amount is very excessive.

### Reason

I think changing how long cars are financed to break the payments up to be more evenly distributed would let more people finance and work towards owning the cars they want, without forcing them to grind for money rather than RP. It would let people not worry about constantly getting money to pay off their car, but rather doing things to slowly work towards paying it off.

**Comment by NotRvgue** [comment]
honestly, sounds like a good idea. no offense the city didn't want grinders. however, say the Dominator GTX for example. 12k down payment on top of 9,000 payment every 12 hours. seems like you don't exactly have a choice but to grind to manage those kinds of payments.
